name: CI

on:
  # No matter for push or pull request events, it would trigger CI for safely saving the source code.
  # For the push event, it only runs building and testing.
  push:
    branches:
      - "your_base_branch"
      - "!**e2e"
      - "!e2e**"
    paths:
#     For GitHub Action
      - ".github/workflows/ci.yaml"
      - ".github/workflows/rw_build_and_test.yaml"
      - ".github/workflows/rw_run_all_test_and_record.yaml"
#     For source code and test
      - "../../abe_plugin/**/*.py"
      - "!**/__pkg_info__.py"
      - "test/**/*.py"
#     For configurations for test or CI
      - ".coveragerc"
      - "codecov.yml"
      - "pytest.ini"
      - "sonar-project.properties"
#     For Python project configuration
      - "pyproject.toml"
      - "uv.lock"

  # For the push event, in addition to build and test would be run, it would trigger other service to keep the reports
  # or other checking, i.e., record the test report by CodeCov and check the code quality by SonarQube.
  pull_request:
    branches:
      - "your_base_branch"
      - "!**e2e"
      - "!e2e**"
    paths:
#     For GitHub Action
      - ".github/workflows/ci.yaml"
      - ".github/workflows/rw_build_and_test.yaml"
      - ".github/workflows/rw_run_all_test_and_record.yaml"
#     For source code and test
      - "../../abe_plugin/**/*.py"
      - "!**/__pkg_info__.py"
      - "test/**/*.py"
#     For configurations for test or CI
      - ".coveragerc"
      - "codecov.yml"
      - "pytest.ini"
      - "sonar-project.properties"
#     For Python project configuration
      - "pyproject.toml"
      - "uv.lock"

jobs:
  build-and-test_all:
#    name: Run all tests and organize all test reports
    uses: ./.github/workflows/rw_run_all_test_and_record.yaml
    with:
      with-environment-variables: 'ABE_TEST_CHANNEL_ID="${{ vars.ABE_TEST_CHANNEL_ID }}"'
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      e2e_test_api_token: ${{ secrets.ABE_SERVICE_TOKEN }}
